ezpublish:
    http_cache:
        purge_type: local
    imagemagick:
        enabled: true
        path: /usr/bin/convert
    siteaccess:
        match:
            URIElement: '1'
stash:
    caches:
        default:
            drivers: %cache_drivers%
            inMemory: %cache_inmemory%
            registerDoctrineAdapter: false
