ezpublish:
    http_cache:
        purge_type: local
    imagemagick:
        enabled: true
        path: /usr/bin/convert
    siteaccess:
        match:
            URIElement: '1'
    system:
        eng:
            languages:
                - eng-GB
            session:
                name: eZSESSID
        ezdemo_site:
            languages:
                - eng-GB
                - fre-FR
            session:
                name: eZSESSID
        fre:
            languages:
                - fre-FR
                - eng-GB
            session:
                name: eZSESSID
stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
